lawconnect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('', views.home_view, name='home'),
    path('submit_case/', views.submit_case_view, name='submit_case'),
    path('my_cases/', views.my_cases_view, name='my_cases'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('change_status/<int:case_id>/', views.change_case_status, name='change_case_status'),
    path('update_case/<int:case_id>/', views.update_case, name='update_case'),
    path('delete_case/<int:case_id>/', views.delete_case, name='delete_case'),
    path('about/', views.about_view, name='about'),
    path('chat/<int:case_id>/', views.chat_view, name='chat_view'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Case(models.Model):
    CATEGORY_CHOICES = [
        ('Civil', 'Civil'),
        ('Criminal', 'Criminal'),
        ('Family', 'Family'),
        ('Divorce', 'Divorce'),
        ('Corporate', 'Corporate'),
        ('Intellectual Property', 'Intellectual Property'),
        ('Employment', 'Employment'),
        ('Tax', 'Tax'),
        ('Real Estate', 'Real Estate'),
        ('Bankruptcy', 'Bankruptcy'),
        ('Other', 'Other'),
    ]

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('resolved', 'Resolved'),
        ('closed', 'Closed'),
        ('rejected', 'Rejected'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cases')
    title = models.CharField(max_length=255)
    description = models.TextField()
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='pending')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} ({self.user.username})"

class Message(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE, related_name='messages')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['timestamp']

    def __str__(self):
        return f"{self.sender.username}: {self.text[:30]}"
    

    

main_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Case ,Message

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Mate:
        modal = User
        fields = ['username', 'email',
                  'password1', 'password2']
        
class CaseForm(forms.ModelForm):
    class Meta:
        model = Case
        fields = ['title', 'description', 'category']
        
class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 2, 'placeholder': 'Type your message here...'}),
        }
        

main_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from .forms import CustomUserCreationForm , CaseForm, MessageForm
from .models import Case, Message
from django.http import HttpResponseForbidden

# Create your views here.

def register_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('home')
        else:
            return render(request, 'login.html', {'error': 'Invalid credentials'})
    return render(request, 'login.html')

def logout_view(request):
    logout(request)
    return redirect('login')


def home_view(request):
    return render(request, 'home.html')

@login_required
def submit_case_view(request):
    if request.method == 'POST':
        form = CaseForm(request.POST)
        if form.is_valid():
            case = form.save(commit=False)
            case.user = request.user
            case.save()
            return redirect('my_cases')
    else:
        form = CaseForm()
    return render(request, 'submit_case.html', {'form': form})

@login_required
def my_cases_view(request):
    cases = Case.objects.filter(user=request.user)
    return render(request, 'my_cases.html', {'cases': cases})

@login_required
def update_case(request, case_id):
    case = get_object_or_404(Case, id=case_id, user=request.user)
    
    if case.status != 'pending':
        return HttpResponseForbidden("You cannot update this case.")
    
    if request.method == 'POST':
        form = CaseForm(request.POST, instance=case)
        if form.is_valid():
            form.save()
            return redirect('my_cases')
    else:
        form = CaseForm(instance=case)
    return render(request, 'update_case.html', {'form': form, 'case': case})

@login_required
def delete_case(request, case_id):
    case = get_object_or_404(Case, id=case_id, user=request.user)
    
    if case.status != 'pending':
        return HttpResponseForbidden("You cannot delete this case.")
    if request.method == 'POST':
        case.delete()
        return redirect('my_cases')
    return render(request, 'delete_case.html', {'case': case})

@staff_member_required
def admin_dashboard(request):
    cases = Case.objects.all().order_by('-created_at')
    return render(request, 'admin_dashboard.html', {'cases': cases})

@staff_member_required
def change_case_status(request, case_id):
    case = get_object_or_404(Case, id=case_id)
    if request.method == 'POST':
        new_status = request.POST.get('status')
        if new_status in dict(Case.STATUS_CHOICES).keys():
            case.status = new_status
            case.save()
    return redirect('admin_dashboard')
    
def about_view(request):
    return render(request, 'about.html')    

@login_required
def chat_view(request, case_id):
    case = get_object_or_404(Case, id=case_id)
    
    if request.user != case.user and not request.user.is_staff:
        return HttpResponseForbidden("You do not have permission to view this case.")
    
    messages = case.messages.all()
    form = MessageForm()

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            msg = form.save(commit=False)
            msg.user = request.user
            msg.case = case
            msg.save()
            return redirect('chat_view', case_id=case.id)
        
    return render(request, 'chat.html', {'case': case, 'messages': messages, 'form': form})
           

main_app/templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Me - Lawyer</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navbar fixed-navbar">
    <div class="nav-right">
        <a href="{% url 'home' %}" class="logo">
            <img src="{% static 'images/logo.png' %}" alt="LawConnect Logo" class="logo-icon">
        </a>

        <a href="{% url 'home' %}">Home</a>
        {% if request.user.is_authenticated %}
            {% if not request.user.is_staff %}
                <a href="{% url 'my_cases' %}">My Cases</a>
                <a href="{% url 'submit_case' %}">Submit Case</a>
            {% else %}
                <a href="{% url 'admin_dashboard' %}">Dashboard</a>
            {% endif %}
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'register' %}">Register</a>
        {% endif %}
        <a href="{% url 'about' %}">About</a>
    </div>
</nav>

    <div class="about-container">
        <div class="about-text">
            <h2>About the Lawyer</h2>
            <p>Hello, I'm <strong>Mr. Hasan Al-Hulaibi</strong>, a dedicated lawyer committed to helping clients with various legal matters.</p>

            <p>I specialize in areas such as:</p>
            <ul>
                <li>Family Law (Divorce, Custody, Inheritance)</li>
                <li>Criminal Law</li>
                <li>Commercial Disputes</li>
                <li>Labor & Employment Cases</li>
                <li>Real Estate and Civil Affairs</li>
            </ul>

            <p>Through <strong>LawConnect</strong>, I aim to make legal support more accessible to individuals in need, with a secure and direct communication system.</p>

            <p>If you wish to submit a case, please <a href="{% url 'register' %}">Register</a> or <a href="{% url 'login' %}">Login</a> to get started.</p>

            <a href="{% url 'home' %}">Back to Home</a>
        </div>
        <div class="about-image">
            <img src="{% static 'images/lawyer.png' %}" alt="Lawyer Hasan" />
        </div>
    </div>

    <footer>
        <p>&copy; 2025 LawConnect.GA. All rights reserved.</p>
    </footer>
</body>
</html>

main_app/templates/admin_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Lawyer Dashboard</title>
</head>
<body>
    <h2 class="container">Admin Dashboard</h2>
 <div class="main-container">
    
    <h3>Welcome, {{ request.user.username | capfirst }}! Here are the submitted cases:</h3>
 </div>
    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>User</th>
                <th>Category</th>
                <th>Description</th>
                <th>Status</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
           {% for case in cases %}
    <tr>
        <td>{{ case.title }}</td>
        <td>{{ case.user.username }}</td>
        <td>{{ case.get_category_display }}</td>
        <td>{{ case.description }}</td>
        <td>
            <form method="post" action="{% url 'change_case_status' case.id %}">
                {% csrf_token %}
                <select name="status" onchange="this.form.submit()">
                    {% for key, value in case.STATUS_CHOICES %}
                        <option value="{{ key }}" {% if case.status == key %}selected{% endif %}>{{ value }}</option>
                    {% endfor %}
                </select>
            </form>

            {% if case.status == 'in_progress' %}
                <a href="{% url 'chat_view' case.id %}" class="chat-link">Chat</a>
            {% endif %}
        </td>
        <td>{{ case.created_at }}</td>
    </tr>
             {% endfor %}

        </tbody>
    </table>

    <br>
    <a   href="{% url 'home' %}">Back to Home</a>
    <a href="{% url 'logout' %}">Logout</a>

    <br>
    <footer>
        <p>&copy; 2025 LawConnect.GA All rights reserved.</p>
    </footer>
</body>
</html>

main_app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}LawConnect{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <div class="main-container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

main_app/templates/chat.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat - Case</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>



<div class="chat-container">
    <h2 class="chat-title">Chat - Case: {{ case.title }}</h2>

    <div class="chat-box">
        {% for msg in messages %}
            <div class="chat-message">
                <p><strong>{{ msg.user.username | capfirst }}:</strong> {{ msg.text }}</p>
                <small>{{ msg.timestamp }}</small>
            </div>
        {% empty %}
            <p class="no-messages">No messages yet.</p>
        {% endfor %}
    </div>

    <form method="post" class="chat-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="chat-button">Send</button>
    </form>

    <a href="{% url 'home' %}" class="chat-back-link">Back to Home</a>
</div>
{% endblock %}
</body>
</br>
<footer>
    <p>&copy; 2025 LawConnect.GA All rights reserved.</p>
</footer>

main_app/templates/delete_case.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Delete The Case</title>
</head>
<body>
    <h2 class="container">Delete Case</h2>
    <div class="main-container">
    <p>Are you sure you want to delete the case titled "{{ case.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirm Delete</button>
    </form>
    <br>
    <a href="{% url 'my_cases' %}">Back to My Cases</a>
    <a href="{% url 'home' %}">Back to Home</a>
    </div>
    <br>    
    <footer>
        <p>&copy; 2025 LawConnect.GA All rights reserved.</p>
    </footer>
</body>
</html>

main_app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Home</title>
</head>
<body>
    
    

<nav class="navbar fixed-navbar">
    <div class="nav-right">
        <a href="{% url 'home' %}" class="logo">
            <img src="{% static 'images/logo.png' %}" alt="LawConnect Logo" class="logo-icon">
        </a>

        <a href="{% url 'home' %}">Home</a>
        {% if request.user.is_authenticated %}
            {% if not request.user.is_staff %}
                <a href="{% url 'my_cases' %}">My Cases</a>
                <a href="{% url 'submit_case' %}">Submit Case</a>
            {% else %}
                <a href="{% url 'admin_dashboard' %}">Dashboard</a>
            {% endif %}
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'register' %}">Register</a>
        {% endif %}
        <a href="{% url 'about' %}">About</a>
    </div>
</nav>



<div class="main-container">
    <h1 class="container">Welcome to LawConnect</h1>
     {% if request.user.is_authenticated %}
        <h3>Hello, {{ request.user.username | capfirst }}!</h3>
        {% if request.user.is_staff%}
        <div class="admin-container">
            <p>You are logged in as a <strong>Lawyer (Admin)</strong>.</p>
            <a href="{% url 'admin_dashboard' %}">Admin Dashboard</a>
            <a href="{% url 'logout' %}">Logout</a>
        </div>
        {% else %}
        <div class="user-container">
            <p>You are logged in as a user.</p>
            <a href="{% url 'my_cases' %}">My Cases</a>
            <a href="{% url 'submit_case' %}">Submit a New Case</a>
            <a href="{% url 'logout' %}">Logout</a>
        </div>
        {% endif %}
        
    {% else %}
    <div class="login-container">
        <p>You are not logged in.</p>
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'register' %}">Register</a>
    </div>  
    {% endif %}
    <h2>About LawConnect</h2>
    <p>LawConnect is a platform that connects users with legal professionals to help them with their legal cases. You can submit your cases, view your submitted cases, and manage your account.</p>
    <h2>Features</h2>
    <ul>
        <li>Submit new legal cases</li>
        <li>View your submitted cases</li>
        <li>Connect with legal professionals</li>
        <li>Manage your account</li>
    </ul>
    <h2>Contact Us</h2>
    <p>If you have any questions or need assistance, please contact us at support@law   connect.com.</p>
</div>
    <br>
    <footer>
        <p>&copy; 2025 LawConnect.GA All rights reserved.</p>
    </footer>           
</body>

main_app/templates/login.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Login</title>
</head>
<body>

    <nav class="navbar fixed-navbar">
    <div class="nav-right">
        <a href="{% url 'home' %}" class="logo">
            <img src="{% static 'images/logo.png' %}" alt="LawConnect Logo" class="logo-icon">
        </a>

        <a href="{% url 'home' %}">Home</a>
        {% if request.user.is_authenticated %}
            {% if not request.user.is_staff %}
                <a href="{% url 'my_cases' %}">My Cases</a>
                <a href="{% url 'submit_case' %}">Submit Case</a>
            {% else %}
                <a href="{% url 'admin_dashboard' %}">Dashboard</a>
            {% endif %}
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'register' %}">Register</a>
        {% endif %}
        <a href="{% url 'about' %}">About</a>
    </div>
</nav>

<div class="main-container">
    <h2 class="container">Login</h2>
    {% if error %}
    <P style="color:red">{{ error }}</p>
    {% endif %}
 <div class="form-container">
    <form method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username" required><br>
        <input type="password" name="password" placeholder="Password" required><br>
        <button type="submit">Login</button>
    </form>
 </div>

    <p>Don't have an account? <a href="{% url 'register' %}">Register here</a></p>
    <br>
    <a href="{% url 'home' %}">Back to Home</a>
</div>
    <footer>
        <p>&copy; 2025 LawConnect.GA All rights reserved.</p>
    </footer>   

</body>

main_app/templates/my_cases.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>My Case</title>
</head>
<body>
    <nav class="navbar fixed-navbar">
    <div class="nav-right">
        <a href="{% url 'home' %}" class="logo">
            <img src="{% static 'images/logo.png' %}" alt="LawConnect Logo" class="logo-icon">
        </a>

        <a href="{% url 'home' %}">Home</a>
        {% if request.user.is_authenticated %}
            {% if not request.user.is_staff %}
                <a href="{% url 'my_cases' %}">My Cases</a>
                <a href="{% url 'submit_case' %}">Submit Case</a>
            {% else %}
                <a href="{% url 'admin_dashboard' %}">Dashboard</a>
            {% endif %}
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'register' %}">Register</a>
        {% endif %}
        <a href="{% url 'about' %}">About</a>
    </div>
</nav>

    <h2 class="container">My Cases</h2>
    
    {% if cases %}
    <div class="case-list">
        <ul>
            {% for case in cases %}
    <li>
        <strong>{{ case.title }}</strong> - {{ case.get_category_display }} - {{ case.get_status_display }}
        <p>{{ case.description }}</p>
        <small>submitted on: {{ case.created_at }}</small><br>

        {% if case.get_status_display == 'Pending' %}
    <a href="{% url 'update_case' case.id %}">Update</a> |
    <a href="{% url 'delete_case' case.id %}">Delete</a>
        {% endif %}


        {% if case.status == 'in_progress' %}
            <a href="{% url 'chat_view' case.id %}" class="chat-link">Chat</a>
        {% endif %}
    </li>
          {% endfor %}

        </ul>
    {% else %}
        <p>You have no cases submitted.</p>
    {% endif %}
    <br>
    <a href="{% url 'submit_case' %}">Submit a New Case</a>
    <a href="{% url 'home' %}">Back to Home</a>
    <a href="{% url 'logout' %}">Logout</a>
    </div>
    <footer>
        <p>&copy; 2025 LawConnect.GA All rights reserved.</p>
    </footer>
</body>
</html>

                
              

main_app/templates/register.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Register</title>
</head>
<body>
    <nav class="navbar fixed-navbar">
    <div class="nav-right">
        <a href="{% url 'home' %}" class="logo">
            <img src="{% static 'images/logo.png' %}" alt="LawConnect Logo" class="logo-icon">
        </a>

        <a href="{% url 'home' %}">Home</a>
        {% if request.user.is_authenticated %}
            {% if not request.user.is_staff %}
                <a href="{% url 'my_cases' %}">My Cases</a>
                <a href="{% url 'submit_case' %}">Submit Case</a>
            {% else %}
                <a href="{% url 'admin_dashboard' %}">Dashboard</a>
            {% endif %}
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'register' %}">Register</a>
        {% endif %}
        <a href="{% url 'about' %}">About</a>
    </div>
</nav>

    <h2 class="container">Register</h2>
<div class="form-container">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
  

    <p>Already have an account? <a href="{% url 'login' %}">Login here</a></p>
    <br>
    <a href="{% url 'home' %}">Back to Home</a>
</div>
    <footer>
        <p>&copy; 2025 LawConnect.GA All rights reserved.</p>
    </footer>
</body>
</html>

main_app/templates/submit_case.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Submit a New Case</title>
</head>
<body>
    <nav class="navbar fixed-navbar">
    <div class="nav-right">
        <a href="{% url 'home' %}" class="logo">
            <img src="{% static 'images/logo.png' %}" alt="LawConnect Logo" class="logo-icon">
        </a>

        <a href="{% url 'home' %}">Home</a>
        {% if request.user.is_authenticated %}
            {% if not request.user.is_staff %}
                <a href="{% url 'my_cases' %}">My Cases</a>
                <a href="{% url 'submit_case' %}">Submit Case</a>
            {% else %}
                <a href="{% url 'admin_dashboard' %}">Dashboard</a>
            {% endif %}
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'register' %}">Register</a>
        {% endif %}
        <a href="{% url 'about' %}">About</a>
    </div>
</nav>

    <h2 class="container">Submit a New Case</h2>
 <div class="form-container">
        
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit Case</button>
    </form>
 

    <a href="{% url 'home' %}">Back to Home</a>
 </div>
</body>
<footer>
    <p>&copy; 2025 LawConnect.GA All rights reserved.</p>
</footer>

main_app/templates/update_case.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Update Your Case</title>
</head>
<body>
    <h2 class="container">Update Your Case</h2>
    <div class="main-container">
    <h3>Update the details of your case titled "{{ case.title }}".</h3> 
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Case</button>
    </form>
    <br>
    <a href="{% url 'my_cases' %}">Back to My Cases</a>
    <a href="{% url 'home' %}">Back to Home</a>
    </div>
    <br>    
    <footer>
        <p>&copy; 2025 LawConnect.GA All rights reserved.</p>
    </footer>
</body>
</html>